from setuptools import setup, find_packages

setup(
    name="deforestation-detection",
    version="0.1.0",
    description="Machine learning project for deforestation detection using Sentinel-2 satellite imagery",
    author="Your Name",
    author_email="your.email@example.com",
    packages=find_packages(),
    install_requires=[
        "rasterio>=1.3.0",
        "numpy>=1.21.0",
        "pandas>=1.3.0",
        "geopandas>=0.10.0",
        "matplotlib>=3.5.0",
        "scikit-learn>=1.0.0",
        "scikit-image>=0.19.0",
        "earthengine-api>=0.1.300",
        "sentinelsat>=1.1.0",
        "requests>=2.28.0",
        "gdal>=3.4.0",
        "pyproj>=3.3.0",
        "shapely>=1.8.0",
        "fiona>=1.8.0",
        "h5py>=3.6.0",
        "netcdf4>=1.5.8",
        "xarray>=0.20.0",
        "schedule>=1.1.0",
        "APScheduler>=3.9.0",
        "pyyaml>=6.0",
        "python-dotenv>=0.19.0",
        "tqdm>=4.62.0",
        "click>=8.0.0",
    ],
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Scientific/Engineering :: GIS",
        "Topic :: Scientific/Engineering :: Image Processing",
    ],
    keywords="satellite imagery, deforestation, machine learning, remote sensing, NDVI",
)
